# Generated by Django 5.1.7 on 2025-03-09 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_message_from_user_remove_message_to_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='chats.ConversationParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
