# Generated by Django 5.1.7 on 2025-03-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_conversation_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='edited_by',
            new_name='edited',
        ),
    ]
